spring:
  datasource:
    url: jdbc:postgres://localhost:5432/blitterdb
    user: blitz
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
