spring:
  sql.init.mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/blitterdb
    username: blitz
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: create-drop
    show-sql: "true"
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

logging.level.org.hibernate:
  SQL: debug
  orm.jdbc.bind: trace
