spring:
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/blitterdb
    username: blitz
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: create-drop
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
management.endpoints.web.exposure.include: prometheus,health,info,metric
# management:
#   influx:
#     metrics:
#       export:
#         org: com.augtheo.blitter
#         bucket: blitter
#         token: lovecraftian
#         uri: http://localhost:8086
logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace
