spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testuser
    password: testpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

