services:
  blitter-api:
    build: blitter-api
    restart: always
    # secrets:
    #   - db-password
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      # - SPRING_PROFILES_ACTIVE=ssl
    ports:
      - 8080:8080
    networks:
      - react-spring
      - spring-postgresql
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - 5342:5342
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "schwifty", "-U", "rick"]
      interval: 5s
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgresql
  blitter-web:
    build:
      context: blitter-web
      # target: development
    ports:
      - 3000:3000
    volumes:
      - ./blitter-web/src:/app/src
    #   - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - blitter-api
    # expose:
    #   - 3306
    #   - 33060
volumes:
  db-data: {}
# secrets:
#   db-password:
#     file: db/password.txt
networks:
  react-spring: {}
  spring-postgresql: {}

