services:
  blitter-api:
    build: blitter-api
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - spring-postgresql
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgresql
  blitter-web:
    build:
      context: blitter-vite
    volumes:
      - /project/node_modules
    depends_on:
      - blitter-api
    restart: always
volumes:
  db-data: {}
networks:
  spring-postgresql: {}
