services:
  blitter-api:
    build: blitter-api
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - react-spring
      - spring-postgresql
  db:
    image: postgres
    ports:
      - 5342:5342
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "schwifty", "-U", "rick"]
      interval: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgresql
  blitter-web:
    build:
      context: blitter-web
    volumes:
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - blitter-api
volumes:
  db-data: {}
networks:
  react-spring: {}
  spring-postgresql: {}

